### ISSUE TITLE
Station lookup fails, and website not displaying results

### ISSUE THREAD

**Issue by Hadyn98** [paulhulme/simpletraintimes#1]
Apologies that this is the incorrect place to highlight this, but as of around 19 June 2019 , the website https://simpletraintimes.co.uk  no longer recognises train stations in the search boxes , and putting 2 stations into the URL also no longer works.

It's been a very useful website , but I appreciate that hosting costs and there is no revenue generation.

**Comment by paulhulme** [comment]
This is the right place to post Hadyn98.
Apologies simpletraintimes has been down. Turns out having an expired credit card on your Azure account eventually catches up with you!
I'm trying to resolve this and get it back up, but I started a new job last week and I've been really busy :/

**Comment by paulhulme** [comment]
Sorted now!

**Comment by Hadyn98** [comment]
Thanks Paul , that's great yes it's working.  I just wanted to say thank you for maintaining a server for this, it's a great website - simple and provides the right level of info in a fast loading page.

**Comment by paulhulme** [comment]
Glad you like it!
Tell your friends ;)

**Comment by Hadyn98** [comment]
Hi Paul

Hope you are well. Just to let you know I've noticed that the platform
details are always TBA even for trains leaving in the next minute or so.

It's been happening for some days now, and at both my stations.

Thought you'd like to know.

Regards
Hadyn

**Comment by paulhulme** [comment]
It seems OK for me, what stations are you using?

**Comment by Hadyn98** [comment]
waterloo and surbiton

I've looked here at waterloo and clapham junction:

[image: image.png]

even the train leaving that minute 11:24 is TBA.

H

**Comment by paulhulme** [comment]
There seems to be a problem with the data feed, that I can't do much about.

There's no platform information on any apps for waterloo:
http://ojp.nationalrail.co.uk/service/ldbboard/dep/WAT

**Comment by Hadyn98** [comment]
Thanks for checking Paul, I've checked
https://simpletraintimes.co.uk/edb/to/dee   and yes I see platforms.
Strange how some stations aren't working !

Thanks for your app again, use it twice a day :-)
